import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';
import {defaultConfig,normalizeConfig} from '../core/config.mjs';
import {createPresentation} from '../core/ppt.mjs';
const dir=await mkdtemp(path.join(tmpdir(),'palette-check-'));const config={...defaultConfig,colors:{background:'#123456',accent:'#abcdef',text:'#fedcba'},title:'JSON 自定义标题'};const file=path.join(dir,'config.json');await writeFile(file,JSON.stringify(config));
assert.equal(normalizeConfig(config).colors.accent,'#ABCDEF');assert.throws(()=>normalizeConfig({...config,colors:{...config.colors,text:'red'}}));assert.throws(()=>normalizeConfig({...config,unknown:true}));
const cli=(...args)=>execFileSync(process.execPath,['cli/palette-ppt.mjs',...args],{encoding:'utf8'});
cli('validate','--config',file);const output=path.join(dir,'cli.pptx');cli('generate','--config',file,'--output',output);assert.throws(()=>cli('generate','--config',file,'--output',output));
const installation=path.join(dir,'installed-skill');cli('install-skill','--dir',installation);const skill=execFileSync(process.execPath,[path.join(installation,'scripts/palette-ppt.mjs'),'example'],{encoding:'utf8'});assert.equal(JSON.parse(skill).version,1);assert.throws(()=>cli('install-skill','--dir',installation));
const client=new Client({name:'palette-integration-check',version:'1.0.0'});await client.connect(new StdioClientTransport({command:process.execPath,args:[path.resolve('cli/mcp.mjs')]}));try{const list=await client.listTools();assert.deepEqual(list.tools.map(t=>t.name).sort(),['generate_ppt','get_palette_example','validate_palette']);const ex=await client.callTool({name:'get_palette_example',arguments:{}});assert.equal(JSON.parse(ex.content[0].text).version,1);const valid=await client.callTool({name:'validate_palette',arguments:{config}});assert.equal(JSON.parse(valid.content[0].text).colors.background,'#123456');const bad=await client.callTool({name:'validate_palette',arguments:{config:{colors:{background:'bad'}}}});assert.equal(bad.isError,true);const gen=await client.callTool({name:'generate_ppt',arguments:{config,outputPath:path.join(dir,'mcp.pptx')}});assert.equal(gen.isError,undefined);const duplicate=await client.callTool({name:'generate_ppt',arguments:{config,outputPath:path.join(dir,'mcp.pptx')}});assert.equal(duplicate.isError,true);}finally{await client.close();}
const JSZip=(await import('jszip')).default;for(const name of ['cli.pptx','mcp.pptx']){const zip=await JSZip.loadAsync(await readFile(path.join(dir,name)));const slides=Object.keys(zip.files).filter(n=>/^ppt\/slides\/slide\d+\.xml$/.test(n));assert.equal(slides.length,10);const xml=await zip.file(slides[0]).async('string');assert.ok(xml.includes('123456'));assert.ok(xml.includes('JSON 自定义标题'));}console.log('PASS: JSON validation, CLI generation, overwrite protection, skill installation and invocation, MCP discovery/validation/generation, PPTX content.');
