import PptxGenJS from 'pptxgenjs';
import {normalizeConfig,slideStyles} from './config.mjs';
export {slideStyles};
export function createPresentation(input,style){const config=normalizeConfig(input);if(!slideStyles.includes(style))style=config.style;const bold=style==='bold',ed=style==='editorial',bento=style==='bento';const colors={bg:config.colors.background,accent:config.colors.accent,text:config.colors.text},title=config.title,subtitle=config.subtitle;const pptx=new PptxGenJS();pptx.layout='LAYOUT_WIDE';pptx.author='色页';pptx.subject='可编辑的配色演示模板';pptx.title=title.replace(/\n/g,'');pptx.theme={headFontFace:ed?'Georgia':'Microsoft YaHei',bodyFontFace:'Microsoft YaHei'};const bg=colors.bg.slice(1),ac=colors.accent.slice(1),tx=colors.text.slice(1);const mx=ed?1.5:.8;const ph=(s,x,y,w,h,label='图片占位')=>{s.addShape(pptx.ShapeType.rect,{x,y,w,h,fill:{color:bg,transparency:100},line:{color:ac,width:1.25,dashType:'dash'}});s.addText(label,{x,y,w,h,align:'center',valign:'middle',fontSize:14,color:ac,charSpacing:2});};
 for(let i=0;i<10;i++){const s=pptx.addSlide();s.background={color:bg};s.addText('STUDIO / PRESENTATION',{x:.7,y:.45,w:6,h:.3,fontSize:11,color:tx,charSpacing:ed?3:2});s.addText(String(i+1).padStart(2,'0')+' / 10',{x:11.2,y:6.9,w:1.4,h:.2,fontSize:10,color:tx});
  if(bold){s.addShape(pptx.ShapeType.rect,{x:0,y:6.9,w:13.34,h:.6,fill:{color:ac},line:{color:ac,transparency:100}});}else if(bento){s.addShape(pptx.ShapeType.line,{x:0,y:.92,w:13.34,h:0,line:{color:ac,width:.75,transparency:35}});s.addShape(pptx.ShapeType.line,{x:0,y:6.55,w:13.34,h:0,line:{color:ac,width:.75,transparency:35}});}else{s.addShape(pptx.ShapeType.line,{x:.7,y:6.7,w:11.9,h:0,line:{color:tx,transparency:ed?55:65,width:.5}});}
  if(i===0||i===9){
   if(bold){s.addShape(pptx.ShapeType.ellipse,{x:8.7,y:1.05,w:4.9,h:4.9,fill:{color:ac},line:{color:ac,transparency:100}});s.addShape(pptx.ShapeType.ellipse,{x:9.5,y:1.85,w:3.3,h:3.3,fill:{color:ac,transparency:60},line:{color:ac,transparency:100}});}
   else if(bento){s.addShape(pptx.ShapeType.line,{x:8.55,y:.92,w:0,h:5.63,line:{color:ac,width:.75,transparency:35}});s.addShape(pptx.ShapeType.line,{x:8.55,y:3.75,w:4.79,h:0,line:{color:ac,width:.75,transparency:35}});s.addShape(pptx.ShapeType.rect,{x:9.05,y:4.15,w:3.85,h:1.95,fill:{color:ac},line:{color:ac,transparency:100}});}
   else{s.addShape(pptx.ShapeType.arc,{x:8,y:1.25,w:4.5,h:4.5,rotate:ed?0:25,line:{color:ac,width:ed?6:10},fill:{color:bg,transparency:100}});}
   if(ed)s.addShape(pptx.ShapeType.line,{x:1.05,y:2.1,w:0,h:3.1,line:{color:ac,width:1}});
   s.addText(i===0?title:'谢谢观看。',{x:mx,y:2,w:8,h:2.1,fontSize:bold?48:44,bold:!ed,italic:false,color:tx,breakLine:false,fontFace:ed?'Georgia':'Microsoft YaHei'});
   s.addText(i===0?subtitle:'让下一次表达，从好配色开始。',{x:mx,y:4.5,w:8,h:.6,fontSize:17,color:ac,charSpacing:ed?2:0});}
  if(i===1){if(bento)s.addShape(pptx.ShapeType.rect,{x:mx,y:1.6,w:2.1,h:1.3,fill:{color:bg,transparency:100},line:{color:ac,width:1,transparency:30}});s.addText('01',{x:mx,y:1.6,w:bento?2.1:3.5,h:bold?2.2:1.3,fontSize:bold?150:bento?52:86,italic:ed,align:bento?'center':'left',valign:bento?'middle':'top',color:ac,fontFace:ed?'Georgia':'Microsoft YaHei'});s.addText('从一个好想法开始',{x:mx,y:3.3,w:11,h:1,fontSize:bold?42:38,bold:!ed,color:tx,fontFace:ed?'Georgia':'Microsoft YaHei'});s.addText('背景洞察 / 目标方向 / 创意策略',{x:mx,y:4.7,w:10,h:.5,fontSize:18,color:ac,charSpacing:ed?2:0});}
  if(i===2){s.addText('把想法变成清晰的表达',{x:mx,y:1.25,w:11,h:.8,fontSize:bold?36:32,bold:!ed,color:tx,fontFace:ed?'Georgia':'Microsoft YaHei'});['洞察需求','建立连接','创造价值'].forEach((t,j)=>{const cx=mx+j*4.1;if(ed)s.addShape(pptx.ShapeType.line,{x:cx,y:2.7,w:3.5,h:0,line:{color:ac,width:1}});if(bento)s.addShape(pptx.ShapeType.rect,{x:cx,y:2.55,w:3.75,h:3.1,fill:{color:bg,transparency:100},line:{color:ac,width:1,transparency:35}});const px=bento?cx+.25:cx,py=bento?.25:0;s.addText('0'+(j+1),{x:px,y:2.8+py,w:3.5,h:.7,fontSize:bento?13:30,bold,italic:ed,color:ac,charSpacing:bento?2:0,fontFace:ed?'Georgia':'Microsoft YaHei'});s.addText(t,{x:px,y:3.7+py,w:3.5,h:.6,fontSize:24,bold:!ed,color:tx,fontFace:ed?'Georgia':'Microsoft YaHei'});s.addText('在这里添加你的核心观点，\n让内容与视觉共同传递价值。',{x:px,y:4.6+py,w:3.3,h:1,fontSize:15,color:tx});});}
  if(i===3){s.addText('每一次进步，都值得看见',{x:mx,y:1.2,w:11,h:.8,fontSize:bold?36:32,bold:!ed,color:tx,fontFace:ed?'Georgia':'Microsoft YaHei'});if(bento)s.addShape(pptx.ShapeType.line,{x:.7,y:5.82,w:11.9,h:0,line:{color:ac,width:.75,transparency:35}});[42,65,58,86].forEach((v,j)=>{s.addShape(pptx.ShapeType.rect,{x:1+j*2.9,y:5.8-v/28,w:bold?2.1:ed?1.1:bento?1.4:1.65,h:v/28,line:{color:ac,transparency:100},fill:{color:ac,transparency:j===3?0:bold?25:30}});s.addText(v+'%',{x:1+j*2.9,y:5.1-v/28,w:2,h:.5,fontSize:23,bold,color:tx});s.addText('Q'+(j+1),{x:1+j*2.9,y:6,w:2,h:.4,fontSize:14,color:tx});});}
  if(i===4){s.addText('用一张图，说清一件事',{x:mx,y:1.25,w:11,h:.8,fontSize:bold?36:32,bold:!ed,color:tx,fontFace:ed?'Georgia':'Microsoft YaHei'});ph(s,mx,2.35,12.5-mx-0.03,3.6,'全幅图片占位 · 16:9');s.addText('图片说明文字 —— 下载模板后在 PowerPoint 中替换为真实图片。',{x:mx,y:6.1,w:11,h:.4,fontSize:13,color:tx,charSpacing:ed?2:0});}
  if(i===5){s.addText('图文混排，讲透一个观点',{x:mx,y:1.5,w:6,h:1.6,fontSize:bold?34:30,bold:!ed,color:tx,fontFace:ed?'Georgia':'Microsoft YaHei'});s.addText('在这里展开你的论述，\n右侧图片与文字相互印证，\n让表达既有逻辑也有画面感。',{x:mx,y:3.4,w:5.6,h:2,fontSize:15,color:tx});ph(s,7.2,1.5,5.3,4.6);}
  if(i===6){s.addText('两种方案，直观对比',{x:mx,y:1.25,w:11,h:.8,fontSize:bold?36:32,bold:!ed,color:tx,fontFace:ed?'Georgia':'Microsoft YaHei'});['方案 A','方案 B'].forEach((t,j)=>{ph(s,.8+j*6.1,2.3,5.6,3.5);s.addText(t+' · 图片说明',{x:.8+j*6.1,y:6,w:5.6,h:.4,fontSize:13,color:tx});});}
  if(i===7){s.addText('“在此填入你的核心引言，\n让它成为全场记住的一句话。”',{x:1.8,y:2.5,w:9.73,h:1.8,fontSize:bold?38:34,bold:!ed,italic:ed,align:'center',color:tx,fontFace:ed?'Georgia':'Microsoft YaHei'});s.addText('—— 作者 / 出处',{x:1.8,y:4.7,w:9.73,h:.5,fontSize:16,align:'center',color:ac,charSpacing:2});}
  if(i===8){s.addText('认识背后的团队',{x:mx,y:1.25,w:11,h:.8,fontSize:bold?36:32,bold:!ed,color:tx,fontFace:ed?'Georgia':'Microsoft YaHei'});[['张晓','创意总监'],['李维','策略负责人'],['陈安','设计主管']].forEach(([n,r],j)=>{ph(s,.8+j*4.1,2.2,3.5,3.2,'照片占位');s.addText(n,{x:.8+j*4.1,y:5.55,w:3.5,h:.5,fontSize:20,bold:!ed,color:tx,fontFace:ed?'Georgia':'Microsoft YaHei'});s.addText(r,{x:.8+j*4.1,y:6.1,w:3.5,h:.4,fontSize:14,color:ac});});}}
 return pptx;
}
